### ISSUE TITLE
拍照时报错

### ISSUE THREAD

**Issue by 694120752** [wsm2015/cutAvator#1]
[ERROR] : IndexSizeError (DOM Exception 1): The index is not in the allowed range.
mui手机拍照后 获取不到图片 报这个错

[ERROR] : TypeError: undefined is not an object (evaluating 'event.touches[0].clientX')
滑动时报这个错

以上使用的手机为 iphone5s  iOS10.2
拍照后img的src为：
img_obj.src:file:///var/mobile/Containers/Data/Application/6802AB75-9915-4906-B0E2-E8D03E56FC48/Documents/Pandora/apps/HBuilder/www/html/main/mine/_doc/photo_003.png
望解决

**Comment by wsm2015** [comment]
1.本项目测试环境是android手机，iphone手机获取不到图片可以根据mui案例获取图片。
2.滑动时报错是用的低级的获取坐标的方法，可以用Hammer.js移动框架解决。
